name: crons
on:
  schedule:
    - cron: "* */12 * * *"
jobs:
  cron:
    runs-on: ubuntu-latest
    steps:
      - name: Sync Glucose Data Cron
        run: |
          curl --request POST \
           --header "Content-Type: application/json" \
           --data '{"apiKey":"${{ secrets.API_KEY }}"}' \
           --url 'https://andreas.fyi/api/syncGlucoseData'
